site_name: OARC-Rutgers
site_url: https://rutgers-oarc.github.io/training
repo_url: https://github.com/rutgers-oarc/training
pages:
  - Home: 'index.md'
  - Amarel User Guide:
      - Amarel Guide: 'Amarel_User_Guide.md'
      - Examples: 'Cluster_Examples.md'
  - HowTo: 
      - Jupyter: 'howtos/jupyter.md' 
      - FastX: 'howtos/fastx.md'
  - Workshops: 
      - Genomics: 'workshops/workshop.md'
      - Labs: 'workshops/Labs.md'
  - R tutorial: 'ressentials.md'
  - Resources: 'resources.md'
  - CheatSheet: 'CheatSheet.md'
theme: rtd-dropdown
