site_name: OARC-Rutgers
repo_url: https://github.com/rutgers-oarc/training
pages:
  - Home: 'index.md'
  - HowTo: 'howto.md' 
  - Workshops: 'workshop.md'
  - R tutorial: 'ressentials.md'
  - Resources: 'resources.md'
  - CheatSheet: 'cheatsheet.md'
theme: readthedocs
