site_name: OARC-Rutgers
site_url: https://rutgers-oarc.github.io/training
repo_url: https://github.com/rutgers-oarc/training
pages:
  - Home: 'index.md'
  - Cluster Guides: 'guides/Cluster_User_Guide.md'
  - Examples: 'guides/Cluster_Examples.md'
  - Community: 'guides/community_resources.md'
  - HowTo: 
      - Jupyter: 'howtos/jupyter.md' 
      - FastX: 'howtos/fastx.md'
  - R tutorial: 'ressentials.md'
  - Cheat Sheets: 'CheatSheet.md'
  - Resources: 'resources.md'
theme: 
  name: 'rtd-dropdown'
